// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
//
// Generated by StoriesListBuilder (stories-list-builder.ts)
// @generated SignedSource<<27aae2df1178eae9895ea6de668f9397>>
//
// This script contains a list of story files to be dynamically loaded by our
// component library.

const FilesList: string[] = [
  'app/components/button.stories.tsx',
  'app/components/buttonBar.stories.tsx',
  'app/components/loadingTriangle.stories.tsx',
  'app/components/logoSentry.stories.tsx',
  'app/components/replays/pageBanner.stories.tsx',
  'app/icons/icons.stories.tsx',
];

export {FilesList};
