// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
//
// Generated by StoriesListBuilder (stories-list-builder.ts)
// @generated SignedSource<<8bc8dcd728278a400bdc9858b45f6b43>>
//
// This script contains a list of story files to be dynamically loaded by our
// component library.

const FilesList: string[] = [
  'app/components/badge.stories.tsx',
  'app/components/button.stories.tsx',
  'app/components/buttonBar.stories.tsx',
  'app/components/featureBadge.stories.tsx',
  'app/components/loadingTriangle.stories.tsx',
  'app/components/logoSentry.stories.tsx',
  'app/components/platformIcon.stories.tsx',
  'app/components/replays/pageBanner.stories.tsx',
  'app/icons/icons.stories.tsx',
];

export {FilesList};
